project:
  type: website
  output-dir: docs

website:
  title: "GIS Miszczyszyn - Jakub Miszczyszyn"
  navbar:
    logo: logo.png
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/j-miszczyszyn
      - icon: linkedin
        href: https://linkedin.com/in/j-miszczyszyn
      - icon: "fa-brands fa-orcid"
        href: https://orcid.org/0009-0002-8592-946X

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
