project:
  type: website
  output-dir: docs

website:
  title: "Jakub Miszczyszyn"
  navbar:
    logo: logo.png
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/j-miszczyszyn
      - icon: linkedin
        href: https://linkedin.com/in/j-miszczyszyn
      - text: "<img src='assets/icons/orcid.svg' alt='ORCID' style='height: 20px; vertical-align: middle; margin-bottom: 4px;'>"
        href: https://orcid.org/0009-0002-8592-946X

format:
  html:
    theme: cosmo
    css: styles.css
