project:
  type: website
  output-dir: docs
website:
  title: "GIS Miszczyszyn - Jakub Miszczyszyn"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - text: "Wykresy"
        href: wykresy.qmd       
    logo: logo.png
    
format:
  html:
    theme: cosmo
    css: styles.css


  